v3.12.0 latest documentation

diff --git a/release_docs b/release_docs
--- a/release_docs
+++ b/release_docs
@@ -39,6 +39,11 @@ cd -
 # Regerenate tutorial.py field_analysis.py
 if [[ $2 = "latest" ]] || [[ $2 = "archive" ]] ; then
   ./test_tutorial_code
+  rc=$?
+  if [[ $rc != 0 ]]; then
+    echo "test_tutorial_code failed."
+    # exit $rc
+  fi
 fi
 
 # --------------------------------------------------------------------
