v3.14.1 documentation

diff --git a/release_docs b/release_docs
--- a/release_docs
+++ b/release_docs
@@ -49,23 +49,23 @@ zip cf_tutorial_files.zip *.nc *.pp
 cd -
 
 # Regerenate tutorial.py field_analysis.py
-if [[ $1 = "latest" ]] || [[ $1 = "archive" ]] ; then
-  ./test_tutorial_code
-  rc=$?
-  if [[ $rc != 0 ]]; then
-    echo "test_tutorial_code failed."
-    # exit $rc
-  fi
-  pre-commit run --files tutorial.py field_analysis.py 
-fi
+#if [[ $1 = "latest" ]] || [[ $1 = "archive" ]] ; then
+#  ./test_tutorial_code
+#  rc=$?
+#  if [[ $rc != 0 ]]; then
+#    echo "test_tutorial_code failed."
+#    # exit $rc
+#  fi
+#  pre-commit run --files tutorial.py field_analysis.py 
+#fi
 
 # --------------------------------------------------------------------
 # Make the latest docs    
 # --------------------------------------------------------------------
 cd docs
-if [[ $1 = "latest" ]] || [[ $1 = "archive" ]] || [[ $1 = "dev-clean" ]] ; then
-  rm -fr $dir/.doctrees
-fi
+#if [[ $1 = "latest" ]] || [[ $1 = "archive" ]] || [[ $1 = "dev-clean" ]] ; then
+#  rm -fr $dir/.doctrees
+#fi
 mkdir -p $dir/_downloads
 
 #if [[ $1 = "latest" ]] || [[ $1 = "archive" ]] ; then
@@ -129,7 +129,8 @@ for html_file in "${html_files[@]}"
 do
     for download_file in "${files_to_copy[@]}"
     do
-        sed -i "s|href=\".*\/${download_file##*/}\"|href=\"$destination_dir/${download_file##*/}\"|g" "$html_file"
+#        sed -i "s|href=\".*\/${download_file##*/}\"|href=\"$destination_dir/${download_file##*/}\"|g" "$html_file"
+        sed -i "s|href=\".*\/${download_file##*/}\"|href=\"/cf-python/_downloads/${download_file##*/}\"|g" "$html_file"
     done
 done
 
