sphinx version test

diff --git a/release_docs b/release_docs
--- a/release_docs
+++ b/release_docs
@@ -7,7 +7,13 @@ if [[ $2 ]] ; then
   exit 1
 fi
 
-ersion=`python -c "import cf; print(cf.__version__)"`
+version=`python -c "import cf; print(cf.__version__)"`
+
+sphinx_version=`python -c "import sphinx; print(sphinx.__version__)"`
+if [[ $sphinx_version != "2.4.5"  ]] ; then
+  echo "ERROR: Must use sphinx version 2.4.5. Got $version"
+  exit 3
+fi
 
 if [[ $1 = "latest" ]] ; then 
   dir=$PWD/docs
